# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5-rkcanPIoSe-3OFJjAGosrRYqPs5xX
"""

!pip install paho-mqtt pandas matplotlib numpy plotly

import paho.mqtt.client as mqtt
import json
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
from collections import deque
import time

# Configuration - GANTI DENGAN CREDENTIALS HIVEMQ ANDA
MQTT_BROKER = "91c95e4b1fc04b6f9eb2e90b69199494.s1.eu.hivemq.cloud"
MQTT_PORT = 8883
MQTT_TOPIC = "hidroponik/parsing/data"
MQTT_USERNAME = "hivemq.webclient.1762882388734"
MQTT_PASSWORD = "80M#ZHh5dU<OF1v$.pty"

# Data storage
data_buffer = deque(maxlen=100)  # Simpan 100 data terakhir
latest_data = None

# Callback ketika terkoneksi
def on_connect(client, userdata, flags, rc):
    print(f"✅ Terhubung ke HiveMQ Cloud dengan kode: {rc}")
    client.subscribe(MQTT_TOPIC)
    print(f"📡 Subscribe ke topic: {MQTT_TOPIC}")

# Callback ketika menerima message
def on_message(client, userdata, msg):
    global latest_data
    try:
        payload = msg.payload.decode('utf-8')
        data = json.loads(payload)

        # Tambah timestamp penerimaan
        data['received_at'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Simpan data
        data_buffer.append(data)
        latest_data = data

        print(f"📥 Data diterima: {data['msg_count']} | Suhu: {data['s_max']}°C")

    except Exception as e:
        print(f"❌ Error parsing data: {e}")

# Setup MQTT Client
client = mqtt.Client()
client.username_pw_set(MQTT_USERNAME, MQTT_PASSWORD)
client.tls_set()  # Enable TLS

client.on_connect = on_connect
client.on_message = on_message

# Connect ke broker
print("🔌 Menghubungkan ke HiveMQ Cloud...")
client.connect(MQTT_BROKER, MQTT_PORT, 60)

# Start background thread untuk MQTT
client.loop_start()

print("🚀 MQTT Client berjalan. Menunggu data...")
print("Tekan Ctrl+C untuk berhenti")

def display_latest_data():
    """Tampilkan data terbaru"""
    if latest_data:
        print("\n" + "="*50)
        print("📊 DATA TERBARU DARI ESP32")
        print("="*50)
        print(f"Message Count: {latest_data['msg_count']}")
        print(f"Timestamp: {latest_data['received_at']}")
        print(f"Suhu Maksimum: {latest_data['s_max']}°C")
        print(f"Suhu Minimum: {latest_data['s_min']}°C")
        print(f"Suhu Rata-rata: {latest_data['s_avg']}°C")
        print(f"Status LED: {latest_data['led_status']}")
        print(f"Status Pompa: {latest_data['pompa']}")
        print(f"Status Buzzer: {latest_data['buzzer']}")
        print("="*50)
    else:
        print("❌ Belum ada data yang diterima")

def create_dataframe():
    """Convert buffer data ke DataFrame"""
    if data_buffer:
        df = pd.DataFrame(list(data_buffer))

        # Convert numeric columns
        numeric_cols = ['s_max', 's_min', 's_avg', 'msg_count']
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        # Convert timestamp
        df['received_at'] = pd.to_datetime(df['received_at'])

        return df
    else:
        return pd.DataFrame()

def analyze_temperature_trends():
    """Analisis trend suhu"""
    df = create_dataframe()
    if df.empty:
        print("❌ Tidak ada data untuk dianalisis")
        return

    print("\n" + "="*50)
    print("📈 ANALISIS TREND SUHU")
    print("="*50)

    # Statistik dasar
    print(f"Jumlah Data: {len(df)}")
    print(f"Rentang Waktu: {df['received_at'].min()} hingga {df['received_at'].max()}")
    print(f"Suhu Maksimum Terakhir: {df['s_max'].iloc[-1]:.2f}°C")
    print(f"Suhu Minimum Terakhir: {df['s_min'].iloc[-1]:.2f}°C")
    print(f"Suhu Rata-rata Terakhir: {df['s_avg'].iloc[-1]:.2f}°C")

    # Trend
    if len(df) > 1:
        trend = df['s_max'].iloc[-1] - df['s_max'].iloc[0]
        trend_direction = "naik" if trend > 0 else "turun" if trend < 0 else "stabil"
        print(f"Trend Suhu: {trend_direction} ({trend:+.2f}°C)")

    # Status kontrol
    latest = df.iloc[-1]
    print(f"\n🎛️  STATUS KONTROL TERAKHIR:")
    print(f"  LED: {latest.get('led_status', 'N/A')}")
    print(f"  Pompa: {latest.get('pompa', 'N/A')}")
    print(f"  Buzzer: {latest.get('buzzer', 'N/A')}")

def plot_temperature_data():
    """Plot data suhu"""
    df = create_dataframe()
    if df.empty or len(df) < 2:
        print("❌ Tidak cukup data untuk plotting")
        return

    plt.figure(figsize=(12, 8))

    # Plot suhu
    plt.subplot(2, 1, 1)
    plt.plot(df['received_at'], df['s_max'], 'r-', label='Suhu Maks', marker='o')
    plt.plot(df['received_at'], df['s_avg'], 'g-', label='Suhu Rata-rata', marker='s')
    plt.plot(df['received_at'], df['s_min'], 'b-', label='Suhu Min', marker='^')

    plt.title('📊 TREND SUHU HIDROPONIK')
    plt.ylabel('Suhu (°C)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.xticks(rotation=45)

    # Plot status kontrol
    plt.subplot(2, 1, 2)

    # Convert status ke numeric untuk plotting
    status_map = {'OFF': 0, 'hijau': 1, 'kuning': 2, 'merah': 3, 'ON': 1}
    df['led_numeric'] = df['led_status'].map(status_map)
    df['pompa_numeric'] = df['pompa'].map(status_map)
    df['buzzer_numeric'] = df['buzzer'].map(status_map)

    plt.plot(df['received_at'], df['led_numeric'], 'g-', label='LED', linewidth=3)
    plt.plot(df['received_at'], df['pompa_numeric'], 'b-', label='Pompa', linewidth=2)
    plt.plot(df['received_at'], df['buzzer_numeric'], 'r-', label='Buzzer', linewidth=2)

    plt.title('🎛️ STATUS KONTROL')
    plt.ylabel('Status')
    plt.xlabel('Waktu')
    plt.yticks([0, 1, 2, 3], ['OFF', 'Hijau/ON', 'Kuning', 'Merah'])
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.xticks(rotation=45)

    plt.tight_layout()
    plt.show()

def export_to_csv(filename="data_hidroponik.csv"):
    """Export data ke CSV"""
    df = create_dataframe()
    if not df.empty:
        df.to_csv(filename, index=False)
        print(f"✅ Data berhasil diexport ke {filename}")
        print(f"📁 Jumlah data: {len(df)} records")
    else:
        print("❌ Tidak ada data untuk diexport")

def real_time_monitor(duration=300):
    """Monitoring real-time selama beberapa detik"""
    print(f"🔍 Memulai real-time monitoring selama {duration} detik...")
    print("Tekan Ctrl+C untuk berhenti lebih awal")

    start_time = time.time()
    try:
        while time.time() - start_time < duration:
            if latest_data:
                display_latest_data()

                # Update setiap 5 detik
                if len(data_buffer) % 5 == 0:
                    analyze_temperature_trends()
                    plot_temperature_data()

            time.sleep(2)  # Update setiap 2 detik

    except KeyboardInterrupt:
        print("\n⏹️  Monitoring dihentikan oleh user")

# Fungsi untuk menampilkan dashboard sederhana
def show_dashboard():
    """Tampilkan dashboard data"""
    df = create_dataframe()
    if df.empty:
        print("❌ Belum ada data yang diterima")
        return

    print("\n" + "="*60)
    print("🎯 DASHBOARD MONITORING HIDROPONIK")
    print("="*60)

    # Data terbaru
    latest = df.iloc[-1]
    print(f"📊 DATA TERBARU:")
    print(f"   • Message #: {latest['msg_count']}")
    print(f"   • Waktu: {latest['received_at']}")
    print(f"   • Suhu Maks: {latest['s_max']:.2f}°C")
    print(f"   • Suhu Min: {latest['s_min']:.2f}°C")
    print(f"   • Suhu Rata: {latest['s_avg']:.2f}°C")

    # Status sistem
    print(f"\n🎛️  STATUS SISTEM:")
    print(f"   • LED: {latest['led_status']}")
    print(f"   • Pompa: {latest['pompa']}")
    print(f"   • Buzzer: {latest['buzzer']}")

    # Rekomendasi berdasarkan suhu
    print(f"\n💡 REKOMENDASI:")
    temp = latest['s_max']
    if temp > 35:
        print("   ⚠️  Suhu tinggi! Perhatikan sistem pendingin")
    elif temp > 30:
        print("   ℹ️  Suhu normal, monitor terus")
    else:
        print("   ✅ Suhu optimal")

    print("="*60)

# Contoh analisis statistik lengkap
def comprehensive_analysis():
    df = create_dataframe()
    if df.empty:
        return

    print("\n" + "="*60)
    print("📊 ANALISIS KOMPREHENSIF DATA HIDROPONIK")
    print("="*60)

    # Statistik deskriptif
    print("📈 STATISTIK SUHU:")
    print(df[['s_max', 's_min', 's_avg']].describe())

    # Efisiensi kontrol
    total_messages = len(df)
    pompa_on = len(df[df['pompa'] == 'ON'])
    buzzer_on = len(df[df['buzzer'] == 'ON'])

    print(f"\n⚡ EFISIENSI KONTROL:")
    print(f"Pompa aktif: {pompa_on}/{total_messages} ({pompa_on/total_messages*100:.1f}%)")
    print(f"Buzzer aktif: {buzzer_on}/{total_messages} ({buzzer_on/total_messages*100:.1f}%)")

    # Trend analysis
    print(f"\n📅 TREND ANALYSIS:")
    print(f"Periode monitoring: {df['received_at'].min()} to {df['received_at'].max()}")
    print(f"Data points: {len(df)}")
    print(f"Rate: {len(df)/(df['received_at'].max() - df['received_at'].min()).total_seconds():.2f} data/detik")

# Jalankan analisis komprehensif
comprehensive_analysis()